; PlatformIO Project Configuration
; ESP32-C3 Foxhunt Badge

[platformio]
default_envs = esp32c3-mini

[env:esp32c3-mini]
platform        = espressif32
board           = esp32-c3-devkitm-1
framework       = arduino
monitor_speed   = 115200
upload_speed    = 921600
build_flags     =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=3
    -DBADGE_FW_VERSION=\"0.1.0\"
lib_deps        =
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit SSD1306@^2.5.9
    fastled/FastLED@^3.6.0
